const state={exercise:null,history:[],attempt:0};
const labels={NORMAL_CONDITION:"正常执行条件",FORWARD_POSTCONDITION:"关注方向后置条件",INVERSE_POSTCONDITION:"粉丝方向后置条件",FIRST_USER_MISSING:"id1 不存在",SECOND_USER_MISSING:"id2 不存在",SELF_FOLLOW:"自我关注",DUPLICATE_FOLLOW:"重复关注"};
const $=id=>document.getElementById(id);
function assemble(){let text=state.exercise.template;for(const key of state.exercise.placeholders){const input=document.querySelector(`[data-blank="${key}"]`);text=text.replace(`{{${key}}}`,input?.value.trim()||`{{${key}}}`)}$('submission').value=text}
function buildFields(){const box=$('blank-fields');box.innerHTML='';for(const key of state.exercise.placeholders){const row=document.createElement('div');row.className='field';row.innerHTML=`<label for="blank-${key}">${labels[key]||key}</label><input id="blank-${key}" data-blank="${key}" autocomplete="off" placeholder="填写 JML 表达式">`;row.querySelector('input').addEventListener('input',assemble);box.appendChild(row)}assemble()}
function loadSample(content){let pattern=state.exercise.template.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const key of state.exercise.placeholders){pattern=pattern.replace(`\\{\\{${key}\\}\\}`,`([\\s\\S]*?)`)}const match=content.match(new RegExp(`^${pattern}$`));if(!match){$('feedback-content').textContent='该样例与当前模板不匹配。';$('feedback-content').classList.remove('hidden');return}state.exercise.placeholders.forEach((key,index)=>{document.querySelector(`[data-blank="${key}"]`).value=match[index+1].replace(/\n\s*@\s*/g,' ').trim()});assemble()}
function renderRequirement(text){$('requirement').textContent=text.replace(/^# .*\n+/,'').trim()}
function renderChecks(checks){return `<div class="check-list">${checks.map(x=>`<div class="check ${x.severity==='error'?'error':''}"><strong>${x.code}</strong><br>${x.message}</div>`).join('')}</div>`}
async function submit(){assemble();const submission=$('submission').value;const mode=$('mode').value;const button=$('submit-button');button.disabled=true;$('empty-feedback').classList.add('hidden');$('feedback-content').classList.add('hidden');$('checking').classList.remove('hidden');try{const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submission,mode,history:state.history})});const data=await response.json();if(!response.ok)throw new Error(data.error||'审查失败');state.attempt++;$('feedback-content').innerHTML=renderChecks(data.checks)+`<div>${escapeHtml(data.feedback)}</div>`;$('feedback-content').classList.remove('hidden');state.history.push({submission,feedback:data.feedback,mode});const item=document.createElement('div');item.className='history-item';item.textContent=`第 ${state.attempt} 次提交 · ${mode} · 已保留用于下一轮反馈`; $('history').prepend(item)}catch(error){$('feedback-content').textContent=`暂时无法完成审查：${error.message}`;$('feedback-content').classList.remove('hidden')}finally{$('checking').classList.add('hidden');button.disabled=false}}
function escapeHtml(value){const div=document.createElement('div');div.textContent=value;return div.innerHTML}
function reset(){document.querySelectorAll('[data-blank]').forEach(x=>x.value='');state.history=[];state.attempt=0;$('history').innerHTML='';$('feedback-content').classList.add('hidden');$('empty-feedback').classList.remove('hidden');assemble()}
async function init(){const response=await fetch('/api/exercise');state.exercise=await response.json();$('exercise-title').textContent=state.exercise.title;$('method-name').textContent=state.exercise.method;renderRequirement(state.exercise.requirement);$('mode').value=state.exercise.default_mode;buildFields();const select=$('sample-select');for(const sample of state.exercise.samples||[]){const option=document.createElement('option');option.value=sample.id;option.textContent=sample.label;select.appendChild(option)}select.addEventListener('change',()=>{const sample=state.exercise.samples.find(x=>x.id===select.value);if(sample)loadSample(sample.content)});$('submit-button').addEventListener('click',submit);$('reset-button').addEventListener('click',()=>{select.value='';reset()})}
init().catch(error=>{$('exercise-title').textContent='题目载入失败';$('requirement').textContent=error.message});
